defaults:
  - eval_config
  - _self_

# only relevant when long_term is not enabled
max_mem_frames: 10


datasets:
  d16-val:
    image_directory: ../DAVIS/2016/JPEGImages/Full-Resolution
    mask_directory: ../DAVIS/2016/Annotations/Full-Resolution
    size_directory: ../DAVIS/2016/JPEGImages/480p
    size: 720
    mem_every: 3
  d17-val:
    image_directory: ../DAVIS/2017/trainval/JPEGImages/Full-Resolution
    mask_directory: ../DAVIS/2017/trainval/Annotations/Full-Resolution
    size_directory: ../DAVIS/2017/trainval/JPEGImages/480p
    size: 720
    mem_every: 3
  d17-test-dev:
    image_directory: ../DAVIS/2017/test-dev/JPEGImages/Full-Resolution
    mask_directory: ../DAVIS/2017/test-dev/Annotations/Full-Resolution
    size_directory: ../DAVIS/2017/test-dev/JPEGImages/480p
    size: 720
    mem_every: 3
  y18-val:
    size: 600
    mem_every: 5
  y19-val:
    size: 600
    mem_every: 5
  mose-val:
    size: 720
    mem_every: 3